### ISSUE TITLE
[BUG] - Meerdere toasters laat fadeout en close niet meer werken

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-toaster#88]
**Omschrijf het probleem**
Wanneer we multiple alert's toevoegen in 1 toaster, werkt de fadeout en close van die alert's enkel voor de laatste toaster.

**Hoe te reproduceren**
Stappen om het probleem te reproduceren en indien mogelijks een code snippet:

``` JS
_toaster = <div id="inspraak-toaster" is="vl-toaster" top-right fadeout></div>
_toasterAlert = <vl-alert id="inspraak-alert-toaster" type="error" icon="warning" title="Validatie mislukt" style="display: none" closable></vl-alert>

for (let i = 0; i < promiseArray.length; i++) {
    let toasterAlert = this._toasterAlert.cloneNode(true);
    let p = promiseArray[i];
    render(html`<p>${p.reason}</p>`, toasterAlert);
    toasterAlert.setAttribute('style', 'display:block');
    this._toaster.push(toasterAlert);
}
```

**Gewenst gedrag**
Alle toaster's doen een fadeout en zijn sluitbaar.

**Omgeving (gelieve aan te vullen):**
 - Browser chrome
 - Versie  83.0.4103.116
 - Versie component 3.0.6

**Extra info**
Wanneer ik de alert.disableClosable methode in de push methode van toaster weglaat, is het probleem opgelost (zie disable-disable-close branch)

**Comment by SBylemans** [comment]
De fadeout issue is gerelateerd aan AIV code:

In lib/toaster.js
```
  var _observeToaster = function _observeToaster(event) {
    var toaster = event[0].target,
        firstAlert = toaster.firstElementChild,
        newAlert = toaster.lastElementChild; // detect if alert is added
    if (event[0].addedNodes.length > 0) {
      _addAlert(newAlert);

      _bindCloseButtons(
          newAlert.shadowRoot ?
                newAlert.shadowRoot.querySelectorAll(".".concat(alertCloseClass))
              : newAlert.querySelectorAll(".".concat(alertCloseClass)));
      if (toaster.getAttribute(toasterFadeoutAtt) === 'true') {
        window.setTimeout(function () {
          _removeAlert(newAlert);
        }, 5000);
      }
    } // when five or more alerts are visible

    if (toaster.childElementCount > 5) {
      _removeAlert(firstAlert);
    }
  };
```
verandert naar
```
var _observeToaster = function _observeToaster(event) {
    var toaster = event[0].target,
        firstAlert = toaster.firstElementChild,
        newAlert = toaster.lastElementChild; // detect if alert is added
    if (event[0].addedNodes.length > 0) {
      _addAlert(newAlert);

      _bindCloseButtons(
          newAlert.shadowRoot ?
                newAlert.shadowRoot.querySelectorAll(".".concat(alertCloseClass))
              : newAlert.querySelectorAll(".".concat(alertCloseClass)));
      if (toaster.getAttribute(toasterFadeoutAtt) === 'true') {
        event.forEach(e => e.addedNodes.forEach(node => {
          window.setTimeout(function () {
            _removeAlert(node);
          }, 5000);
        }));
      }
    } // when five or more alerts are visible

    if (toaster.childElementCount > 5) {
      _removeAlert(firstAlert);
    }
  };
```

**Comment by coemans** [comment]
@SBylemans doet het probleem zich nog voor? Op de demo pagina kan ik het probleem niet reproduceren:

![toaster](https://user-images.githubusercontent.com/11139249/90608328-bb651f80-e202-11ea-865e-0b8bdc57c264.gif)

**Comment by SBylemans** [comment]
@coemans het sluiten van de toasters werkt met slechts de laatste wordt door fadeout verwijdert.

**Comment by coemans** [comment]
@SBylemans op de demo pagina lijkt ook dat te werken?

![fade](https://user-images.githubusercontent.com/11139249/90729369-c5505680-e2c6-11ea-9ac0-2aed3b6bd958.gif)

**Comment by SBylemans** [comment]
Bij versie 3.0.5 werkt het nog niet. Om naar 3.0.7 te gaan moeten alle componenten geupdate worden.

**Comment by SBylemans** [comment]
@coemans dit is dus nog niet opgelost, zie IBO

**Comment by coemans** [comment]
Applicatief inderdaad te reproduceren, op de webcomponenten pagina niet. Verder te onderzoeken.

**Comment by coemans** [comment]
Probleem stelt zich blijkbaar alleen wanneer meerdere meldingen tegelijk geactiveerd worden, dus zonder kleine delay die bijvoorbeeld veroorzaakt werd door manueel de meldingen te openen. Probleem was ook reproduceerbaar op webcomponent pagina en zal daar opgelost worden.

**Comment by FreekRombauts** [comment]
@coemans, Ik heb de fix getest maar krijg een beetje raar gedrag in safari dat ik niet goed begrijp. Alle toasters worden toegevoegd, en verdwijnen dan 1 voor 1. Dat loopt goed tot er nog 5 toasters overblijven. Dan is er een lange delay waarna alle 5 toasters tegelijk verdwijnen.

In firefox en chrome is het gedrag nog vreemder. Daar loopt ook alles goed tot er nog 5 toasters overblijven. Dan opnieuw een lange delay, er verdwijnt nog 1 toaster en de laatste 4 blijven staan.

**Comment by coemans** [comment]
@FreekRombauts het gedrag zoals beschreven in Firefox en Chrome kan ik niet reproduceren.

In ieder geval, er worden maximaal 5 foutmeldingen getoond. Vanaf dat er meer foutmeldingen gerenderd worden, zullen de eerste foutmeldingen verwijderd worden. Meer dan 5 foutmeldingen op mobile werkt bijvoorbeeld storend.

Ik adviseer om de foutmeldingen te beperken i.p.v. dit gedrag (centraal) te wijzigen. Voor formulier validatie kan eigenlijk beter de [vl-ui-form-validation](https://github.com/milieuinfo/webcomponent-vl-ui-form-validation) gebruikt worden, waardoor het probleem zich ook niet zal stellen.
